version: '3'

services:
  e2e-website-app:
    image: e2e-website-mails-image
    stdin_open: true
    command: node dist/main.js
    env_file:
      - '.production.env'
    ports:
      - '5001:443'
    networks:
      - e2e-website-mails-backend
    depends_on:
      - db-server-e2e-website-mails
    restart: 'unless-stopped'

  db-server-e2e-website-mails:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: e2e-website-mails_admin
      MONGO_INITDB_ROOT_PASSWORD: 2b0YlZxL79D
      MONGO_INITDB_DATABASE: admin
    ports:
      - '5002:27017'
    networks:
      - e2e-website-mails-backend
    volumes:
      - db-server-e2e-website-mails:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: 'unless-stopped'

networks:
  e2e-website-mails-backend:
    driver: bridge

volumes:
  db-server-e2e-website-mails:
    driver: local
